export const lehnga2=[
  {
    _id:1,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/y/g/m/l-sleeveless-shset95222-shae-by-sassafras-original-imaggjzkwyyyezzg.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Grey",
    selling_price: "2069",
    price: "4599",
    disscount: "55% off",
    size: "",
  },
  {
    _id:2,
    image:
      "https://rukminim1.flixcart.com/image/612/612/knyxqq80/salwar-kurta-dupatta/q/i/q/32-skd7385-biba-original-imag2jag2zzz3shw.jpeg?q=70",
    name: "BIBA",
    qty:0,
    fee:233,
    brand: "Solid Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Yellow",
    selling_price: "4016",
    price: "8995",
    disscount: "55% off",
    size: "",
  },
  {
    _id:3,
    image:
      "https://rukminim1.flixcart.com/image/612/612/krme93k0/lehenga-choli/9/t/e/free-half-sleeve-ghaghra-choli-coconut-original-imag5df5ktsnnypv.jpeg?q=70",
    name: "ZAALIMA FASHION",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Green",
    selling_price: "36",
    price: "1799",
    disscount: "78% off",
    size: "",
  },
  {
    _id:4,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/l/x/d/free-full-sleeve-lehenga-lehenga-for-women-lehenga-choli-net-original-imaggcwfb3pjh2hf.jpeg?q=70",
    name: "Cute Fellow",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Purple",
    selling_price: "65",
    price: "3499",
    disscount: "82% off",
    size: "",
  },
  {
    _id:5,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kp78e4w0/lehenga-choli/n/n/d/free-short-sleeve-baby-pink-choli-trivety-original-imag3hbpwczdj2hu.jpeg?q=70",
    name: "Trivety",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Pink",
    selling_price: "49",
    price: "1999",
    disscount: "78% off",
    size: "",
  },
  {
    _id:6,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/0/m/free-sleeveless-zip1434-zinariya-fab-original-imagnftyaaaqjexa.jpeg?q=70",
    name: "Zinariya Fab",
    qty:0,
    fee:233,
    brand: "Floral Print Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "49",
    price: "3099",
    disscount: "83% off",
    size: "",
  },
  {
    _id:7,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l29c9e80/lehenga-choli/w/c/v/free-sleeveless-gulab02-rhet-fashion-original-imagdmy4cnbc839p.jpeg?q=70",
    name: "jahal fashion",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Red",
    selling_price: "44",
    price: "2499",
    disscount: "80% off",
    size: "",
  },
  {
    _id:8,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l1fc0i80/lehenga-choli/j/k/t/free-half-sleeve-modak-rama-gajri-dishwa-fashion-original-imagczmhzqmzpyy9.jpeg?q=70",
    name: "DECIZE CLOTHING",
    qty:0,
    fee:233,
    brand: "Self Design Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Pink, Green",
    selling_price: "84",
    price: "2099",
    disscount: "59% off",
    size: "",
  },
  {
    _id:9,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/d/i/u/free-half-sleeve-big-tea-blue-trivety-original-imagnyd8rmf9cjqw.jpeg?q=70",
    name: "Trivety",
    qty:0,
    fee:233,
    brand: "Printed Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "49",
    price: "1499",
    disscount: "68% off",
    size: "",
  },
  {
    _id:10,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l4u7vrk0/lehenga-choli/a/z/3/free-3-4-sleeve-jannat-maroon-jahal-fashion-original-imagfnap3f9zmnr3.jpeg?q=70",
    name: "jahal fashion",
    qty:0,
    fee:233,
    brand: "Self Design Semi Stitched Lehenga & Crop Top",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Red",
    selling_price: "44",
    price: "1999",
    disscount: "78% off",
    size: "",
  },
  {
    _id:11,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/f/c/9/s-short-sleeve-shset95212-shae-by-sassafras-original-imaghxqtcqfmxrur.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Embellished Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "White",
    selling_price: "2249",
    price: "4999",
    disscount: "55% off",
    size: "",
  },
  {
    _id:12,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/w/d/z/l-full-sleeve-shset95390-shae-by-sassafras-original-imagk4khzbgchqmn.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Embroidered Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Purple",
    selling_price: "1934",
    price: "4299",
    disscount: "55% off",
    size: "",
  },
  {
    _id:13,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/j/e/6/free-sleeveless-new-designer-embroidred-sequins-heavy-work-original-imaggpy5gzt6m5hg.jpeg?q=70",
    name: "ZAALIMA FASHION",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Dark Blue",
    selling_price: "74",
    price: "1999",
    disscount: "60% off",
    size: "",
  },
  {
    _id:14,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kiw1dow0-0/lehenga-choli/d/d/a/free-half-sleeve-dulhen-7-lehenga-vm-tejani-original-imafykqgmxhzhf9y.jpeg?q=70",
    name: "NJ FASHION",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Red",
    selling_price: "59",
    price: "3999",
    disscount: "85% off",
    size: "",
  },
  {
    _id:15,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/b/k/f/free-full-sleeve-lehenga-lehenga-for-women-lehenga-choli-net-original-imaggcvr8nhqehzf.jpeg?q=70",
    name: "Cute Fellow",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Maroon",
    selling_price: "64",
    price: "3499",
    disscount: "82% off",
    size: "",
  },
  {
    _id:16,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kvba7bk0/lehenga-choli/v/v/m/free-half-sleeve-new-ruffle-designer-lehenga-cholis-for-indian-original-imag88ryhq3gpupc.jpeg?q=70",
    name: "ZAALIMA FASHION",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Grey",
    selling_price: "49",
    price: "1999",
    disscount: "79% off",
    size: "",
  },
  {
    _id:17,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/z/n/q/xs-sleeveless-shset95224-shae-by-sassafras-original-imaggjzgkvheh2ks.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Maroon",
    selling_price: "1919",
    price: "4799",
    disscount: "60% off",
    size: "",
  },
  {
    _id:18,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/j/p/i/xl-full-sleeve-shset95393-shae-by-sassafras-original-imagkmakcztfrrnf.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Purple",
    selling_price: "2114",
    price: "4699",
    disscount: "55% off",
    size: "",
  },
  {
    _id:19,
    image:
      "https://rukminim1.flixcart.com/image/612/612/krntoy80/lehenga-choli/z/n/8/free-3-4-sleeve-future-wine-goroly-original-imag5ezdwczgyb5m.jpeg?q=70",
    name: "GOROLY",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Purple",
    selling_price: "72",
    price: "3999",
    disscount: "80% off",
    size: "",
  },
  {
    _id:20,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kx6fwcw0/lehenga-choli/i/n/z/free-3-4-sleeve-kavya-lehengacholi-012-e-mart-original-imag9zx6ckfnthh5.jpeg?q=70",
    name: "E mart",
    qty:0,
    fee:233,
    brand: "Self Design Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Pink",
    selling_price: "22",
    price: "59",
    disscount: "51% off",
    size: "",
  },
  {
    _id:21,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/s/3/z/s-sleeveless-shset95191-shae-by-sassafras-original-imaghf5krhynk4zq.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga & Crop Top",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Gold",
    selling_price: "1679",
    price: "4199",
    disscount: "60% off",
    size: "",
  },
  {
    _id:22,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kuzuoi80/lehenga-choli/g/4/f/m-short-sleeve-skdnew-age-7662-biba-original-imag7zn2xvyejmr3.jpeg?q=70",
    name: "BIBA",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga & Crop Top",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Dark Blue",
    selling_price: "4800",
    price: "7500",
    disscount: "36% off",
    size: "",
  },
  {
    _id:23,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kt7jv680/lehenga-choli/f/n/i/free-sleeveless-l8097-fashionuma-original-imag6hxffsx8hkgh.jpeg?q=70",
    name: "anara",
    qty:0,
    fee:233,
    brand: "Digital Print Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "59",
    price: "2999",
    disscount: "80% off",
    size: "",
  },
  {
    _id:24,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/9/f/e/free-3-4-sleeve-jivikaaa-001-vajiba-original-imaggzcgrycypkc7.jpeg?q=70",
    name: "vajiba",
    qty:0,
    fee:233,
    brand: "Solid Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Maroon",
    selling_price: "37",
    price: "1999",
    disscount: "82% off",
    size: "",
  },
  {
    _id:25,
    image:
      "https://rukminim1.flixcart.com/image/612/612/k4k7f680/lehenga-choli/c/n/c/free-lc-sansa-shree-impex-original-imafnf74t3peacjm.jpeg?q=70",
    name: "Shree Impex",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Dark Green",
    selling_price: "64",
    price: "5999",
    disscount: "88% off",
    size: "",
  },
  {
    _id:26,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/b/s/2/free-3-4-sleeve-future-morpankh-goroly-original-imag5ez6uxhvwreb.jpeg?q=70",
    name: "GOROLY",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "74",
    price: "3999",
    disscount: "80% off",
    size: "",
  },
  {
    _id:27,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/u/n/b/s-sleeveless-skdrose-bow8586-off-white-biba-original-imagmw9eza8rzrp6.jpeg?q=70",
    name: "BIBA",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "White",
    selling_price: "8995",
    price: "",
    disscount: "",
    size: "",
  },
  {
    _id:28,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/o/x/n/free-na-lehngacholi-2-yuvi-creation-original-imaghgxcrdthfdy4.jpeg?q=70",
    name: "Yuvi Creation",
    qty:0,
    fee:233,
    brand: "Embellished Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Light Blue",
    selling_price: "2239",
    price: "3900",
    disscount: "42% off",
    size: "",
  },
  {
    _id:29,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l19m93k0/lehenga-choli/r/r/3/free-short-sleeve-sb-velentine-s-b-creation-original-imagcvdgh5ptkwuq.jpeg?q=70",
    name: "Anghanbrothers",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Red, Gold",
    selling_price: "92",
    price: "5555",
    disscount: "82% off",
    size: "",
  },
  {
    _id:30,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/n/u/v/free-sleeveless-new-designer-embroidred-sequins-heavy-work-original-imaggbwhhhnmhxxd.jpeg?q=70",
    name: "ZAALIMA FASHION",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Purple",
    selling_price: "79",
    price: "3399",
    disscount: "76% off",
    size: "",
  },
  {
    _id:31,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/u/r/v/free-na-phoshak-25jan-12-yuvi-creation-original-imagmay6w9fy22fb.jpeg?q=70",
    name: "Yuvi Creation",
    qty:0,
    fee:233,
    brand: "Printed Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Red, White",
    selling_price: "99",
    price: "1900",
    disscount: "47% off",
    size: "",
  },
  {
    _id:32,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/z/9/n/xl-sleeveless-skdfestive8249aw22fus-biba-original-imaggtzgkt83qbew.jpeg?q=70",
    name: "BIBA",
    qty:0,
    fee:233,
    brand: "Printed Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Pink",
    selling_price: "4197",
    price: "5995",
    disscount: "29% off",
    size: "",
  },
  {
    _id:33,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l37mtu80/lehenga-choli/c/u/h/free-3-4-sleeve-jannat-maroon02120-r-h-comapany-original-imagedyttdhzpz8j.jpeg?q=70",
    name: "R&H COMAPANY",
    qty:0,
    fee:233,
    brand: "Self Design Semi Stitched Lehenga & Crop Top",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Grey",
    selling_price: "39",
    price: "2499",
    disscount: "86% off",
    size: "",
  },
  {
    _id:34,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/k/8/free-3-4-sleeve-jivikaaa-001-vajiba-original-imaggzbbszb6m54n.jpeg?q=70",
    name: "vajiba",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Red",
    selling_price: "39",
    price: "1999",
    disscount: "82% off",
    size: "",
  },
  {
    _id:35,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/m/q/7/free-half-sleeve-pochampalli-pattu-fabcartz-original-imaggvyj73udeg3h.jpeg?q=70",
    name: "Fabcartz",
    qty:0,
    fee:233,
    brand: "Self Design Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Dark Green",
    selling_price: "99",
    price: "2999",
    disscount: "66% off",
    size: "",
  },
  {
    _id:36,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/d/i/u/free-half-sleeve-big-tea-blue-trivety-original-imagnyd8rmf9cjqw.jpeg?q=70",
    name: "Trivety",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "69",
    price: "2699",
    disscount: "75% off",
    size: "",
  },
  {
    _id:37,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/3/o/3/xl-sleeveless-shset95392-shae-by-sassafras-original-imagkmapsgbgup8r.jpeg?q=70",
    name: "Shae by SASSAFRAS",
    qty:0,
    fee:233,
    brand: "Floral Print Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Dark Blue",
    selling_price: "1679",
    price: "4199",
    disscount: "60% off",
    size: "",
  },
  {
    _id:38,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/0/m/free-sleeveless-zip1434-zinariya-fab-original-imagnftyaaaqjexa.jpeg?q=70",
    name: "Pink She",
    qty:0,
    fee:233,
    brand: "Digital Print Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "40",
    price: "3099",
    disscount: "85% off",
    size: "",
  },
  {
    _id:39,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/f/g/b/free-3-4-sleeve-jivikaaa-001-vajiba-original-imaggzc8mespdkr6.jpeg?q=70",
    name: "vajiba",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Blue",
    selling_price: "31",
    price: "1999",
    disscount: "83% off",
    size: "",
  },
  {
    _id:40,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/x/s/free-full-sleeve-purple-lehenga-ishu-fab-original-imagnzgvgeq85gt8.jpeg?q=70",
    name: "ISHU FAB",
    qty:0,
    fee:233,
    brand: "Embroidered Semi Stitched Lehenga Choli",
     ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:20.4,
    color: "Purple",
    selling_price: "71",
    price: "2499",
    disscount: "71% off",
    size: "",
  },
];
