export const saree=[
    {
         _id:1,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/6/t/z/free-sequined-embroidered-saree-granthva-fab-unstitched-original-imaggsq6b4y2adwk.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "PRATHAM BLUE",
        "brand": "Embroidered Bollywood Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Purple",
        "selling_price": "79",
        "price": "3999",
        "disscount": "80% off"
    },
    {
         _id:2,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/3/j/n/free-silver-gulab-banaras-silk-palace-unstitched-original-imagz2zy2uyj6tp5.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Banaras silk palace",
        "brand": "Woven Banarasi Tissue Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pink",
        "selling_price": "96",
        "price": "3500",
        "disscount": "71% off"
    },
    {
         _id:3,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/z/x/e/free-saree-with-georgette-fabric-sada-sobhagyavati-bhav-with-original-imagjnurkkccy8kg.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Qwarty",
        "brand": "Polka Print, Embroidered, Self Design Bandhani\n                          Georgett...",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Red",
        "selling_price": "34",
        "price": "1798",
        "disscount": "79% off"
    },
    {
         _id:4,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/v/p/3/free-prathna-om-vastra-fab-unstitched-original-imaghmwuprfjubfn.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Rarebeauty",
        "brand": "Embroidered Bollywood Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Black",
        "selling_price": "39",
        "price": "2299",
        "disscount": "85% off"
    },
    {
         _id:5,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/s/u/t/free-matka-04-tejas-sarees-unstitched-original-imagj69c9yy4pcgh.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Tejassarees",
        "brand": "Embellished Bandhani Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Yellow",
        "selling_price": "30",
        "price": "92",
        "disscount": "58% off"
    },
    {
         _id:6,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/5/z/k/free-banarasi-saree-kalapushpi-unstitched-original-imagm5vz25z6fmuj.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Kalapushpi",
        "brand": "Self Design Banarasi Cotton Blend, Pure Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Maroon",
        "selling_price": "47",
        "price": "2899",
        "disscount": "82% off"
    },
    {
         _id:7,
        "image": "https://rukminim1.flixcart.com/image/612/612/k7c88sw0/sari/j/z/y/free-ladli-krishna-r-fashion-original-imafphxuxmkutnt8.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Krishna R fashion",
        "brand": "Woven Bollywood Georgette, Cotton Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pink, Beige",
        "selling_price": "49",
        "price": "3999",
        "disscount": "88% off"
    },
    {
         _id:8,
        "image": "https://rukminim1.flixcart.com/image/612/612/k4hcjgw0/sari/k/n/g/free-10068-h-shaibo-saree-original-imafndx6y8nqcefx.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Shaibo saree",
        "brand": "Checkered Bollywood Cotton Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pack of 2, Multicolor",
        "selling_price": "64",
        "price": "2199",
        "disscount": "71% off"
    },
    {
         _id:9,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/t/x/0/free-prathna-om-vastra-fab-unstitched-original-imag773gmebcc9md.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Rarebeauty",
        "brand": "Embroidered Bollywood Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Blue",
        "selling_price": "25",
        "price": "2007",
        "disscount": "85% off"
    },
    {
         _id:10,
        "image": "https://rukminim1.flixcart.com/image/612/612/kzvlua80/sari/7/s/l/free-sds0030-sadika-unstitched-original-imagbsg4na5x3gfn.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "MATRUCHHAYA",
        "brand": "Embroidered, Woven Daily Wear Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Grey",
        "selling_price": "26",
        "price": "1999",
        "disscount": "85% off"
    },
    {
         _id:11,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/g/m/i/free-60-gram-gulab-saree-adirotz-unstitched-original-imagz88maq2psggy.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Adirotz",
        "brand": "Embroidered Bollywood Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Magenta",
        "selling_price": "49",
        "price": "2599",
        "disscount": "81% off"
    },
    {
         _id:12,
        "image": "https://rukminim1.flixcart.com/image/612/612/l3xcr680/sari/o/h/t/free-if-rgtg-red-pisara-unstitched-original-imagexza4cnczdzj.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Pisara",
        "brand": "Woven Bollywood Organza Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Multicolor",
        "selling_price": "1329",
        "price": "4997",
        "disscount": "73% off"
    },
    {
         _id:13,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/w/5/n/free-pattu-saree-ejoty-fashion-unstitched-original-imag4abzywzyk5ry-bb.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Ejoty Fashion",
        "brand": "Floral Print Bollywood Lycra Blend Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Black",
        "selling_price": "29",
        "price": "2999",
        "disscount": "90% off"
    },
    {
         _id:14,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/7/i/7/free-sari-onestacreation-stitched-original-imagk7kgquderuqk.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "ShiVAdit Ethnic",
        "brand": "Embroidered, Self Design, Applique Banarasi Art Silk,\n                          N...",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Black",
        "selling_price": "69",
        "price": "2499",
        "disscount": "74% off"
    },
    {
         _id:15,
        "image": "https://rukminim1.flixcart.com/image/612/612/l0zm64w0/sari/x/l/p/free-mc-50-rani-kartvya-unstitched-original-imagcnksmzyktamm.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Kartvya",
        "brand": "Woven Kanjivaram Jacquard, Pure Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pink",
        "selling_price": "33",
        "price": "1699",
        "disscount": "78% off"
    },
    {
         _id:16,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/n/5/n/free-2739s251-samah-unstitched-original-imagzj99zuqvmcg6.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Samah",
        "brand": "Printed, Geometric Print, Embellished Daily Wear\n                          Lycra ...",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Black",
        "selling_price": "23",
        "price": "1233",
        "disscount": "77% off"
    },
    {
         _id:17,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/6/r/h/free-sequencee-blackk-radadiyatrd-unstitched-original-imagz4yqwa2vschj.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "RadadiyaTRD",
        "brand": "Self Design Bollywood Georgette, Cotton Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Black",
        "selling_price": "69",
        "price": "2999",
        "disscount": "76% off"
    },
    {
         _id:18,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/z/r/t/free-embellished-daily-wear-georgette-saree-black-famous-zone-original-imaghpqzthrass5u.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "NAMRA TEX",
        "brand": "Embellished Daily Wear Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Black",
        "selling_price": "1299",
        "price": "1999",
        "disscount": "35% off"
    },
    {
         _id:19,
        "image": "https://rukminim1.flixcart.com/image/612/612/l1fc0i80/sari/8/b/s/free-sari-fabwoman-unstitched-original-imagcztprwg9dgvz.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "SNH EXPORT",
        "brand": "Woven Banarasi Silk Blend Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Red",
        "selling_price": "49",
        "price": "2999",
        "disscount": "83% off"
    },
    {
         _id:20,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/saree-fall/l/e/2/medium-embroidered-daily-wear-art-silk-saree-yellow-angelarts-original-imag5cdh6xsfkgyy-bb.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Disha Fashion",
        "brand": "Embroidered Banarasi Art Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Yellow",
        "selling_price": "48",
        "price": "99",
        "disscount": "52% off"
    },
    {
         _id:21,
        "image": "https://rukminim1.flixcart.com/image/612/612/ksyz8280/sari/f/j/2/free-jlk-peacock-4-pink-ab-kayimi-unstitched-original-imag6f5jkgadnhgx.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Kayimi",
        "brand": "Printed Bollywood Art Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pink, Beige",
        "selling_price": "39",
        "price": "1663",
        "disscount": "79% off"
    },
    {
         _id:22,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/x/g/i/free-fl-1199-jsitaliya-unstitched-original-imagc4q5csjac5bq-bb.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "JSItaliya",
        "brand": "Self Design, Embroidered Bollywood Net Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "White",
        "selling_price": "49",
        "price": "1999",
        "disscount": "77% off"
    },
    {
         _id:23,
        "image": "https://rukminim1.flixcart.com/image/612/612/krkyt8w0/saree-fall/f/n/0/medium-embroidered-daily-wear-art-silk-saree-maroon-angelarts-original-imag5ccj7yfkpv5b.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Disha Fashion",
        "brand": "Embroidered Banarasi Art Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Maroon",
        "selling_price": "42",
        "price": "99",
        "disscount": "50% off"
    },
    {
         _id:24,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-sari/m/n/n/free-mineral-chiffon-aishwarya-unstitched-original-imaghd3e53zfgrzu.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Aishwarya",
        "brand": "Printed, Floral Print Daily Wear Chiffon Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Yellow",
        "selling_price": "49",
        "price": "1999",
        "disscount": "77% off"
    },
    {
         _id:25,
        "image": "https://rukminim1.flixcart.com/image/612/612/k7xnukw0/sari/e/8/d/free-khusi-krishna-r-fashion-unstitched-original-imafq22gfteg5gzh.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Krishna R fashion",
        "brand": "Woven Bollywood Jacquard Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pink, Grey",
        "selling_price": "49",
        "price": "3999",
        "disscount": "88% off"
    },
    {
         _id:26,
        "image": "https://rukminim1.flixcart.com/image/612/612/kshtxu80/shopsy-sari/h/i/r/free-1077-red-dhnik-creation-unstitched-original-imag6fnkhgmmqzkx.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Rarebeauty",
        "brand": "Embroidered Bollywood Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Dark Blue",
        "selling_price": "39",
        "price": "1999",
        "disscount": "82% off"
    },
    {
         _id:27,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/s/g/o/free-lfs-44-cream-lasfira-unstitched-original-imagzranmgc79zn2.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "LASFIRA",
        "brand": "Self Design Banarasi Cotton Blend, Jacquard Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Cream",
        "selling_price": "49",
        "price": "2499",
        "disscount": "80% off"
    },
    {
         _id:28,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/d/n/n/free-60-gram-gulab-saree-adirotz-unstitched-original-imagz88mju9uj3h7.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Adirotz",
        "brand": "Embroidered Bollywood Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Blue",
        "selling_price": "49",
        "price": "2599",
        "disscount": "81% off"
    },
    {
         _id:29,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/b/b/w/free-braso2-o-combo-lorofy-unstitched-original-imagkymbfmjbfeqj.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "LOROFY",
        "brand": "Self Design Bollywood Net Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Red",
        "selling_price": "24",
        "price": "1599",
        "disscount": "81% off"
    },
    {
         _id:30,
        "image": "https://rukminim1.flixcart.com/image/612/612/l4ln8nk0/sari/p/2/u/free-2535s934-samah-unstitched-original-imagfgq7pc2mc4vz.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Samah",
        "brand": "Printed, Geometric Print, Embellished Bhagalpuri Silk\n                          B...",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Green, Pink",
        "selling_price": "29",
        "price": "1563",
        "disscount": "81% off"
    },
    {
         _id:31,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/e/a/t/free-lfs-44-light-green-lasfira-unstitched-original-imagzrarausz9jef.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "LASFIRA",
        "brand": "Self Design Banarasi Cotton Blend, Jacquard Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Light Green",
        "selling_price": "41",
        "price": "2499",
        "disscount": "81% off"
    },
    {
         _id:32,
        "image": "https://rukminim1.flixcart.com/image/612/612/ktep2fk0/sari/9/b/g/free-s-01-signagraph-unstitched-original-imag6raqrxtuhgkm.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "signagraph",
        "brand": "Woven Banarasi Pure Silk, Satin Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Maroon",
        "selling_price": "39",
        "price": "3999",
        "disscount": "90% off"
    },
    {
         _id:33,
        "image": "https://rukminim1.flixcart.com/image/612/612/krkyt8w0/sari/y/p/v/free-wedding-saree-ecolors-fab-unstitched-original-imag5c8efuhrjz9t.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Cartyshop",
        "brand": "Embellished Bollywood Georgette, Art Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Light Blue, Blue",
        "selling_price": "37",
        "price": "3999",
        "disscount": "90% off"
    },
    {
         _id:34,
        "image": "https://rukminim1.flixcart.com/image/612/612/kflftzk0-0/sari/o/y/c/free-hitesh2series-fumvel-unstitched-original-imafwypg4fwky3a7.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Jiyan Fashion Retail",
        "brand": "Floral Print Bollywood Lycra Blend Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Maroon, Black",
        "selling_price": "29",
        "price": "2497",
        "disscount": "90% off"
    },
    {
         _id:35,
        "image": "https://rukminim1.flixcart.com/image/612/612/l3929ow0/sari/s/g/u/free-sds030-sadika-unstitched-original-imageev4hm7sxdbc.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "MATRUCHHAYA",
        "brand": "Embroidered, Woven Daily Wear Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Yellow",
        "selling_price": "26",
        "price": "1999",
        "disscount": "85% off"
    },
    {
         _id:36,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/e/u/x/free-silk-samruddhi-unstitched-original-imagg9f2cagzstgz.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "samruddhi",
        "brand": "Woven Kanjivaram Pure Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Red",
        "selling_price": "41",
        "price": "5999",
        "disscount": "92% off"
    },
    {
         _id:37,
        "image": "https://rukminim1.flixcart.com/image/612/612/ksyz8280/sari/3/h/m/free-jlk-peacock-4-red-ab-kayimi-unstitched-original-imag6f5jqghhxdpr.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Kayimi",
        "brand": "Printed Bollywood Art Silk Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Red, Beige",
        "selling_price": "39",
        "price": "1663",
        "disscount": "79% off"
    },
    {
         _id:38,
        "image": "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/8/9/s/free-lfs-60-light-pink-lasfira-unstitched-original-imagnas2g6yhuscx.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "LASFIRA",
        "brand": "Self Design Banarasi Jacquard Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Pink",
        "selling_price": "49",
        "price": "2999",
        "disscount": "83% off"
    },
    {
         _id:39,
        "image": "https://rukminim1.flixcart.com/image/612/612/kxaq7ww0/sari/o/k/q/free-grey-1692-6-kashvi-sarees-unstitched-original-imag9s7ggsjw2gcn.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Anand Sarees",
        "brand": "Printed, Striped Daily Wear Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "White, Black",
        "selling_price": "29",
        "price": "1299",
        "disscount": "76% off"
    },
    {
         _id:40,
        "image": "https://rukminim1.flixcart.com/image/612/612/kqgyhe80/sari/z/j/t/free-greyt-1152-1-kashvi-sarees-unstitched-original-imag4h6mft9kydgv.jpeg?q=70",
        qty:0,
        fee:233,
        "name": "Anand Sarees",
        "brand": "Printed, Floral Print Daily Wear Georgette Saree",
         ranking:'4.2/5 - 43 sold',
        reviews:32,
        oldprice:204,
        "color": "Red",
        "selling_price": "29",
        "price": "1299",
        "disscount": "76% off"
    }
]